### ISSUE TITLE
[BUG] Bangla input doesn't work on any apps

### ISSUE THREAD

**Issue by abirabedinkhan** [ibus/ibus-m17n#80]
**Describe the bug**
when I try to use unibijoy (bangla) it doesn't work. it still shows English char when I try to type

**To Reproduce**
[https://github.com/abdullah-if/ibus-victory-bn](https://github.com/abdullah-if/ibus-victory-bn)
It works on my Ubuntu desktop perfectly fine but now working on the other machine .

**Expected behavior**

**Screenshots or videos**
same as #38 

**ibus-m17n version?**

**m17n-db versions?**
1.8.0

**ibus version?**
IBus 1.5.23

**Distribution and version?**
Debian Buster

**Desktop and version?**
xfce4

**Xorg or Wayland?**
x11

**Comment by mike-fabian** [comment]
bn-bijoyUnicode.mim seems to work fine for me on Fedora 40, ibus-m17n-1.4.29-1.fc40.x86_64, 
ibus-1.5.30-5.fc40.x86_64.
bn-bijoyClassic.mim in your repo looks broken to me, I don't know what this is supposed to be, maybe it has been destroyed by some encoding conversion?

**Comment by abirabedinkhan** [comment]
`bn-bijoyClassic.mim` you have to use specific fonts for that
Yeah it works on my Ubuntu 22.04 machine too but not working on `Debian Buster Xfce arm x11`

**Comment by abirabedinkhan** [comment]
> bn-bijoyUnicode.mim seems to work fine for me on Fedora 40, ibus-m17n-1.4.29-1.fc40.x86_64, ibus-1.5.30-5.fc40.x86_64. bn-bijoyClassic.mim in your repo looks broken to me, I don't know what this is supposed to be, maybe it has been destroyed by some encoding conversion?

none of them work for me on `Debian Buster Xfce arm x11`

**Comment by mike-fabian** [comment]
And what happens? Can you give more details what doesn't work?

**Comment by abirabedinkhan** [comment]
> And what happens? Can you give more details what doesn't work?

normally normal ibus input works but any of the inputs from m17n don't work

**Comment by abirabedinkhan** [comment]
Is there any place where I can find the logs of m17n??

**Comment by mike-fabian** [comment]
ibus-m17n doesn't write any logs unfortunately.

Do any ibus input methods work for you at all? Do you only have problems with bn-bijoyUnicode.mim in ibus-m17n or do other ibus input methods not work either?

is ibus running? What does `ps aux | grep ibus` show?

Can you try to install ibus-typing-booster as well please?

ibus-typing-booster supports all m17n-db input methods supported by ibus-m17n and has a lot more features **and** it writes a log file where we can look if there are problems. 

Here is the user documentation for ibus-typing-booster:

https://mike-fabian.github.io/ibus-typing-booster/docs/user/

Especially look at the `Setup` chapter https://mike-fabian.github.io/ibus-typing-booster/docs/user/#2 to find out how to setup ibus-typing-booster to use bn-bijoyUnicode.mim

**Comment by mike-fabian** [comment]
Here is a screenshot of the ibus-typing-booster setup tool when it is etup to use bn-bijoyUnicode.mim:
 
![Screenshot](https://github.com/ibus/ibus-m17n/assets/2330175/3a9f62a7-acf9-4726-b61f-480559db3c78)

**Comment by mike-fabian** [comment]
So please try ibus-typing-booster to find out whether ibus works at all for you and there is only a specific problem with ibus-m17n or whether it affects all ibus input methods.

**Comment by abirabedinkhan** [comment]
> ibus-m17n doesn't write any logs unfortunately.
> 
> Do any ibus input methods work for you at all? Do you only have problems with bn-bijoyUnicode.mim in ibus-m17n or do other ibus input methods not work either?
> 
> is ibus running? What does `ps aux | grep ibus` show?
> 
> Can you try to install ibus-typing-booster as well please?
> 
> ibus-typing-booster supports all m17n-db input methods supported by ibus-m17n and has a lot more features **and** it writes a log file where we can look if there are problems.
> 
> Here is the user documentation for ibus-typing-booster:
> 
> https://mike-fabian.github.io/ibus-typing-booster/docs/user/
> 
> Especially look at the `Setup` chapter https://mike-fabian.github.io/ibus-typing-booster/docs/user/#2 to find out how to setup ibus-typing-booster to use bn-bijoyUnicode.mim

Yeah **IBUS** works normally with other options but not working with m17n.
```
$ ps aux | grep ibus
saplaos     2469  0.6  0.4 309544  8500 ?        Sl   10:56   0:00 /bin/ibus-daemon
saplaos     2612  0.0  0.3 234432  6580 ?        Sl   10:56   0:00 /usr/libexec/ibus-dconf
saplaos     2613  1.6  1.9 314884 40464 ?        Sl   10:56   0:00 /usr/libexec/ibus-ui-gtk3
saplaos     2616 20.0  1.2 268976 26320 ?        Sl   10:56   0:07 /usr/libexec/ibus-extension-gtk3
saplaos     2622  0.1  0.2 234344  6072 ?        Sl   10:56   0:00 /usr/libexec/ibus-portal
saplaos     2711  1.9  0.8 277892 17060 ?        Sl   10:56   0:00 /usr/libexec/ibus-engine-m17n --ibus
saplaos     3408  0.0  0.0   5908   752 pts/0    S+   10:57   0:00 grep ibus
```

**Comment by abirabedinkhan** [comment]
> So please try ibus-typing-booster to find out whether ibus works at all for you and there is only a specific problem with ibus-m17n or whether it affects all ibus input methods.

When I try to open the setup for the `ibus-typing-booster` it doesn't show an interface like yours that is given in the screenshot.
[Screencast from 26-6-24 11:07:24 পূর্বাহ্ণ +06.webm](https://github.com/ibus/ibus-m17n/assets/67215274/081e4a5d-af00-43ff-8f73-2a4d16a44dd4)

**Comment by mike-fabian** [comment]
The setup tool shown in your screencast is the setup tool of ibus-m17n, not the setup tool of ibus-typing-booster.

There is no ibus-typing-booster seen in this menu:

![Screenshot](https://github.com/ibus/ibus-m17n/assets/2330175/63f7d7a7-da24-451b-ac29-f2ff12f22935)

So you probably need to add ibus-typing-booster with `ibus-setup` as described here for Xfce:

https://mike-fabian.github.io/ibus-typing-booster/docs/user/#1_3  (Chapter "When using other desktops than Gnome3")

**Comment by mike-fabian** [comment]
> Yeah it works on my Ubuntu 22.04 machine too but not working on Debian Buster Xfce arm x11

Is your Ubuntu 22.04 machine also using the arm architecture? Could the problem have something to do with the arm architecture? I have no arm machine available and have never tried ibus-m17n on arm.

**Comment by abirabedinkhan** [comment]
> > Yeah it works on my Ubuntu 22.04 machine too but not working on Debian Buster Xfce arm x11
> 
> Is your Ubuntu 22.04 machine also using the arm architecture? Could the problem have something to do with the arm architecture? I have no arm machine available and have never tried ibus-m17n on arm.

Nope, it's not on an arm machine; it's X86_64. I think the problem's probably on XFCE, as it's also shown on #38.

**Comment by abirabedinkhan** [comment]
> The setup tool shown in your screencast is the setup tool of ibus-m17n, not the setup tool of ibus-typing-booster.
> 
> There is no ibus-typing-booster seen in this menu:
> 
> ![Screenshot](https://private-user-images.githubusercontent.com/2330175/343063880-63f7d7a7-da24-451b-ac29-f2ff12f22935.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk1NTA1MjMsIm5iZiI6MTcxOTU1MDIyMywicGF0aCI6Ii8yMzMwMTc1LzM0MzA2Mzg4MC02M2Y3ZDdhNy1kYTI0LTQ1MWItYWMyOS1mMmZmMTJmMjI5MzUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MjhUMDQ1MDIzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OGM5ZGIxMzc1YTE5M2U1NjdiZDkxN2ExZTViYzBiNGRkMTE5YzAyMWVhOWE5Yjk4ZjlkZDAyMGQxY2NhYzdjNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.mu3vwZ_2kV5uoB0yptFOVfx5IUhTi-Zwf5LxDxM2Aew)
> 
> So you probably need to add ibus-typing-booster with `ibus-setup` as described here for Xfce:
> 
> https://mike-fabian.github.io/ibus-typing-booster/docs/user/#1_3 (Chapter "When using other desktops than Gnome3")

![Screenshot from 2024-06-28 10-59-51](https://github.com/ibus/ibus-m17n/assets/67215274/7e0437bd-c379-4ef7-84d4-b567b541a564)
Nope, not working also!

**Comment by mike-fabian** [comment]
> Nope, it's not on an arm machine; it's X86_64. I think the problem's probably on XFCE, as it's also shown on #38.

https://github.com/ibus/ibus-m17n/issues/38 was about KDE Wayland.

ibus-m17n works just fine for me on XFCE.

**Comment by mike-fabian** [comment]
Did you restart ibus (`ibus restart`) after installing ibus-typing-booster or restart your session (which will also restart ibus)?

To "see" newly installed input methods, ibus needs to be restarted.

In your screenshot of `ibus-setup`, you correctly search for `booster` and get no results. I think that means that on the command line you would not get this result either:

```
mfabian@hathi:~
$ ibus list-engine | grep booster
  typing-booster - Typing Booster
mfabian@hathi:~
$ 
```

Did you `sudo apt-get install ibus-typing-booster` finish without problems?

Then (after an `ibus restart`!) `ibus list-engine | grep booster` should show you that ibus now knows ibus-typing-booster and then you should be able to add it in `ibus-setup`.

**Comment by mike-fabian** [comment]
OK, so `ibus list-engine` lists it correctly. The search in ibus-setup in old versions of ibus didn‘t work so well, my guess is that your search for `booster` does not work because this old version of ibus-setup does not do a substring search.

You can try searching for the complete string, `typing-booster` or `Typing Booster`.

Or, after clicking on the  three vertical dots ⋮ don't search but just scroll down until you find the `Other` section (ibus-typing-booster is in the `Other` section because it can work for many languages, therefore it is not in the section for any particular language). If you then open this `Other` section and scroll through it, you should find  `Typing Booster` somewhere.

**Comment by mike-fabian** [comment]
![Screenshot](https://github.com/ibus/ibus-m17n/assets/2330175/05b82df3-8404-43ac-9ff8-fe7b153231c3)

**Comment by mike-fabian** [comment]
![Screenshot](https://github.com/ibus/ibus-m17n/assets/2330175/6784c49b-0ee5-4d7c-83b9-e7599d0b0f1a)

**Comment by mike-fabian** [comment]
@abirabedinkhan Did you make any progress? Could you add ibus-typing-booster now? Do you have any more details why ibus-m17n doesn’t work for you with bn-bijoyUnicode.mim? Does ibus-m17n work with other m17n input methods?  For example, does it work with any of the other Bengali m17n input methods?:

```
$ ls /usr/share/m17n/bn*.mim -1
/usr/share/m17n/bn-disha.mim
/usr/share/m17n/bn-inscript.mim
/usr/share/m17n/bn-inscript2.mim
/usr/share/m17n/bn-itrans.mim
/usr/share/m17n/bn-national-jatiya.mim
/usr/share/m17n/bn-probhat.mim
/usr/share/m17n/bn-unijoy.mim
```

or you could try a very simple m17n input method like `t-latn-post`, using that with ibus-m17n you should be able to type `u"` and get `ü`.

Does any of this work?

Maybe you can make more screenshots or videos to show what your setup is and what goes wrong?

**Comment by mike-fabian** [comment]
Does it still not work for you? Do you h ave any more information?

**Comment by abirabedinkhan** [comment]
nope still not able to make it work

**Comment by abirabedinkhan** [comment]
> @abirabedinkhan Did you make any progress? Could you add ibus-typing-booster now? Do you have any more details why ibus-m17n doesn’t work for you with bn-bijoyUnicode.mim? Does ibus-m17n work with other m17n input methods? For example, does it work with any of the other Bengali m17n input methods?:
> 
> ```
> $ ls /usr/share/m17n/bn*.mim -1
> /usr/share/m17n/bn-disha.mim
> /usr/share/m17n/bn-inscript.mim
> /usr/share/m17n/bn-inscript2.mim
> /usr/share/m17n/bn-itrans.mim
> /usr/share/m17n/bn-national-jatiya.mim
> /usr/share/m17n/bn-probhat.mim
> /usr/share/m17n/bn-unijoy.mim
> ```
> 
> or you could try a very simple m17n input method like `t-latn-post`, using that with ibus-m17n you should be able to type `u"` and get `ü`.
> 
> Does any of this work?
> 
> Maybe you can make more screenshots or videos to show what your setup is and what goes wrong?

yeah I'm gonna try that and let you konw

**Comment by abirabedinkhan** [comment]
I did this
```
saplaos@BongoPC:~$ ls /usr/share/m17n/bn*.mim -1
/usr/share/m17n/bn-bijoyClassic.mim
/usr/share/m17n/bn-bijoyUnicode.mim
/usr/share/m17n/bn-disha.mim
/usr/share/m17n/bn-inscript.mim
/usr/share/m17n/bn-itrans.mim
/usr/share/m17n/bn-probhat.mim
/usr/share/m17n/bn-unijoy.mim
saplaos@BongoPC:~$ 
```
how can I do the `t-latn-post` thing?

**Comment by mike-fabian** [comment]
You should have this file:

```
mfabian@hathi:~
$ ls /usr/share/m17n/latn-post.mim 
/usr/share/m17n/latn-post.mim
mfabian@hathi:~
```

And ibus should be able to list latn-post:

```
mfabian@hathi:~
$ ibus list-engine | grep latn-post
  m17n:t:latn-post - t-latn-post (m17n)
mfabian@hathi:~
$ 
```

Then you can add the `t-latn-post` input method using `ibus-setup`.

Like in this video:

https://github.com/user-attachments/assets/3295ea67-91d5-43a1-ab2c-dcf9ceab5f6d

In this video I use `ibus-setup` to add the `t-latn-post` input method, then select it in the panel.
After that, I type `u"` into the terminal and the result is `ü`.

**Comment by mike-fabian** [comment]
Very similar you should be able to add ibus-typing-booster using `ibus-setup`, just scroll down to the `Other` section after `Add` and look for Typing Booster there.

**Comment by abirabedinkhan** [comment]
still doesn't work!
https://drive.google.com/file/d/1dKnX6ACM1eaLt1SV9Ez9kIoimumwD6-D/view?usp=sharing

**Comment by mike-fabian** [comment]
I see that you could successfully add the `t-latn-post` input method and select it in the panel, but it doesn't work in the terminal.

How are the environment variables related to ibus set?

What do you get when you type `env | grep ibus` into the terminal?

```
mfabian@hathi:~
$ env | grep ibus
GLFW_IM_MODULE=ibus
GTK_IM_MODULE=ibus
XMODIFIERS=@im=ibus
QT_IM_MODULE=ibus
mfabian@hathi:~
$ 
```

**Comment by abirabedinkhan** [comment]
`env | grep ibus` doesn't return any output but in my `.bashrc` file it is configured.
```
saplaos@BongoPC:~$ cat .bashrc 
# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

# don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=ignoreboth
GTK_IM_MODULE=ibus
QT_IM_MODULE=ibus
XMODIFIERS=@im=ibus

# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=1000
HISTFILESIZE=2000

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# If set, the pattern "**" used in a pathname expansion context will
# match all files and zero or more directories and subdirectories.
#shopt -s globstar

# make less more friendly for non-text input files, see lesspipe(1)
#[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# set variable identifying the chroot you work in (used in the prompt below)
if [ -z "${debian_chroot:-}" ] && [ -r /etc/debian_chroot ]; then
    debian_chroot=$(cat /etc/debian_chroot)
fi

# set a fancy prompt (non-color, unless we know we "want" color)
case "$TERM" in
    xterm-color|*-256color) color_prompt=yes;;
esac

# uncomment for a colored prompt, if the terminal has the capability; turned
# off by default to not distract the user: the focus in a terminal window
# should be on the output of commands, not on the prompt
#force_color_prompt=yes

if [ -n "$force_color_prompt" ]; then
    if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
	# We have color support; assume it's compliant with Ecma-48
	# (ISO/IEC-6429). (Lack of such support is extremely rare, and such
	# a case would tend to support setf rather than setaf.)
	color_prompt=yes
    else
	color_prompt=
    fi
fi

if [ "$color_prompt" = yes ]; then
    PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
else
    PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w\$ '
fi
unset color_prompt force_color_prompt

# If this is an xterm set the title to user@host:dir
case "$TERM" in
xterm*|rxvt*)
    PS1="\[\e]0;${debian_chroot:+($debian_chroot)}\u@\h: \w\a\]$PS1"
    ;;
*)
    ;;
esac

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    #alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'

    #alias grep='grep --color=auto'
    #alias fgrep='fgrep --color=auto'
    #alias egrep='egrep --color=auto'
fi

# colored GCC warnings and errors
#export GCC_COLORS='error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01'

# some more ls aliases
alias ll='ls -l'
alias la='ls -A'
alias l='ls -CF'

# Alias definitions.
# You may want to put all your additions into a separate file like
# ~/.bash_aliases, instead of adding them here directly.
# See /usr/share/doc/bash-doc/examples in the bash-doc package.

if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export LANGUAGE=en_US.UTF-8
```

```
saplaos@BongoPC:~$ env | grep ibus
saplaos@BongoPC:~$ 
```

**Comment by abirabedinkhan** [comment]
I fixed it somehow now it's returning the values
```
saplaos@BongoPC:~$ env | grep ibus
GTK_IM_MODULE=ibus
XMODIFIERS=@im=ibus
QT_IM_MODULE=ibus
saplaos@BongoPC:~$ 
```

**Comment by abirabedinkhan** [comment]
after fixing that issues still no luck with those input methods. they are still not working.

**Comment by abirabedinkhan** [comment]
> I fixed it somehow now it's returning the values
> 
> ```
> saplaos@BongoPC:~$ env | grep ibus
> GTK_IM_MODULE=ibus
> XMODIFIERS=@im=ibus
> QT_IM_MODULE=ibus
> saplaos@BongoPC:~$ 
> ```

i apparently didn't add `export` before those env variables.

**Comment by mike-fabian** [comment]
And is it working after adding the export?

These variables might still not be set in the  terminal you are trying to use because when the terminal was started, `.bashrc` was not yet read. `.bashrc` is for interactive shells. Starting up your desktop was not interactive.

From the terminal, where see these variables correct now when checking with `env | grep ibus`, please start another terminal by typing `xfce4-terminal &` and then try whether you can type into that new terminal. The new terminal had these variables correctly set in the environment when it was started.

If that  helps and if you can use ibus in the new  terminal, then add the setting of these environment variables to `~/.profile` (or maybe `~/.bash_profile` or `~/.bash_login` if you are already using one of these.

See the man page of bash:

```
       When bash is invoked as an interactive login shell, or as a  non-interactive  shell
       with  the  --login  option,  it  first  reads  and  executes commands from the file
       /etc/profile, if  that  file  exists.   After  reading  that  file,  it  looks  for
       ~/.bash_profile,  ~/.bash_login,  and ~/.profile, in that order, and reads and exe‐
       cutes commands from the first one that exists and is readable.  The --noprofile op‐
       tion may be used when the shell is started to inhibit this behavior.

       When an interactive login shell exits, or a non-interactive  login  shell  executes
       the  exit  builtin  command,  bash  reads  and  executes  commands  from  the files
       ~/.bash_logout and /etc/bash.bash_logout, if the files exists.

       When an interactive shell that is not a login shell is started, bash reads and exe‐
       cutes commands from ~/.bashrc, if that file exists.  This may be inhibited by using
       the --norc option.  The --rcfile file option will force bash to  read  and  execute
       commands from file instead of ~/.bashrc.
```

**Comment by abirabedinkhan** [comment]
nope, it's still not working!

**Comment by mike-fabian** [comment]
Even starting gedit like `env GTK_IM_MODULE=ibus gedit` does not make it work in  gedit?

You wrote above:

> Yeah IBUS works normally with other options but not working with m17n.

So which ibus input methods are actually working for you?

**Comment by abirabedinkhan** [comment]
>So which ibus input methods are actually working for you?

All of the IBus input methods are working perfectly fine but m17n methods are not working.


>Even starting gedit like env `GTK_IM_MODULE=ibus` gedit does not make it work in gedit?

Nope

**Comment by mike-fabian** [comment]
> > So which ibus input methods are actually working for you?
> 
> All of the IBus input methods are working perfectly fine but m17n methods are not working.

Which ones especially have you tried? Did you try ibus-typing-booster already? Because that would give you  the same input methods as ibus-m17n does.
> > Even starting gedit like env `GTK_IM_MODULE=ibus` gedit does not make it work in gedit?
> 
> Nope

**Comment by mike-fabian** [comment]
> > > So which ibus input methods are actually working for you?
> > 
> > 
> > All of the IBus input methods are working perfectly fine but m17n methods are not working.
> 
> Which ones especially have you tried? Did you try ibus-typing-booster already? Because that would give you the same input methods as ibus-m17n does.

In this screenshot from your video, I see **only** m17n input methods from ibus and keyboard layouts.

Those which have the little keyboard icon in ibus-setup in your screenshot are keyboard layouts.

![Screenshot](https://github.com/user-attachments/assets/8b5aa1ed-3a5b-47a9-a1c2-f00560c70d79)

**Comment by abirabedinkhan** [comment]
>Those which have the little keyboard icon in ibus-setup in your screenshot are keyboard layouts.

only with those icons works

**Comment by mike-fabian** [comment]
> > Those which have the little keyboard icon in ibus-setup in your screenshot are keyboard layouts.
> 
> only with those icons works

So only the keyboard layouts work for you, no ibus input methods.

You should be able to add ibus-typing-booster in ibus-setup the same way you added the t-latn-post input method, look in the "Other" section for typing booster. My guess is that it won't work either, because no ibus input methods at all seem to work for you.

**Comment by mike-fabian** [comment]
But ibus-typing-booster at least write a log file which ibus-m17n does not, so **maybe** there is something interesting in the log file.

**Comment by abirabedinkhan** [comment]
![image](https://github.com/user-attachments/assets/d956c701-a670-4216-9d84-732f40b3abbe)
yeah I already installed it how can check or share the logs?

**Comment by mike-fabian** [comment]
Oh, ibus-typing-booster-2.10.5 is **ancient**. Is there nothing newer available?

**Comment by mike-fabian** [comment]
Maybe upgrading to a newer debian version would solve some of your problems?

You wrote that you are using Debian Buster htat is really very old. If possible, update to a newer Debian version, maybe `trixie`.

**Comment by mike-fabian** [comment]
> yeah I already installed it how can check or share the logs?

The Typing booster log file is here:

```
~/.local/share/ibus-typing-booster/debug.log
```

You can attach that log file  here.

You can also follow the end of that log file by doing:

```
tail -F ~/.local/share/ibus-typing-booster/debug.log
```

and then try to use Typing Booster. While using it, new output should appear in the log file.

Please also increase the debug level in the Typing Booster setup tool to 3 or more to get more output in the log file.

**Comment by abirabedinkhan** [comment]
![image](https://github.com/user-attachments/assets/2266a308-728c-4e40-b3e6-718818b0ae57)
![image](https://github.com/user-attachments/assets/fe4ea1bf-7520-456e-8be3-112b7dd5de65)

**Comment by abirabedinkhan** [comment]
well, I'm trying to upgrade to Bookworm using this script https://gist.github.com/rrottmann/b0f371a62950a9e149c4358772c5a647 I'll keep you updated

**Comment by mike-fabian** [comment]
> ![image](https://private-user-images.githubusercontent.com/67215274/401539112-2266a308-728c-4e40-b3e6-718818b0ae57.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzY0MzE1NjYsIm5iZiI6MTczNjQzMTI2NiwicGF0aCI6Ii82NzIxNTI3NC80MDE1MzkxMTItMjI2NmEzMDgtNzI4Yy00ZTQwLWIzZTYtNzE4ODE4YjBhZTU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTA5VDE0MDEwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZhMjdhZGU2YjZiOWJiYWMxY2M5MjhhMzJiNTg4M2YzNGM1N2M3MWU0M2RkZTcyZTBiNzI3YjNjZDUyY2VkYjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.qUp5kOxtReo-_vV380g5Z1ttfL-LinFANv0bR0twjrE) ![image](https://private-user-images.githubusercontent.com/67215274/401539243-fe4ea1bf-7520-456e-8be3-112b7dd5de65.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzY0MzE1NjYsIm5iZiI6MTczNjQzMTI2NiwicGF0aCI6Ii82NzIxNTI3NC80MDE1MzkyNDMtZmU0ZWExYmYtNzUyMC00NTZlLThiZTMtMTEyYjdkZDVkZTY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTA5VDE0MDEwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM0YzEyNjFkMDY0YTJhMTZlYjMwMTcyMzllYjgxOTYwYTM4OTE1ZWI5ZTRjMGQxMWVjOTliMmU3YWI4ZWMzOGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.W6drSkphlXV6qIwVBr-gZffPjSx89V2E2PXYLyODwlw)

If there is no `debug.log` in that directory, then ibus-typing-booster did never run on your system.

**Comment by abirabedinkhan** [comment]
> > ![image](https://private-user-images.githubusercontent.com/67215274/401539112-2266a308-728c-4e40-b3e6-718818b0ae57.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzY0MzE1NjYsIm5iZiI6MTczNjQzMTI2NiwicGF0aCI6Ii82NzIxNTI3NC80MDE1MzkxMTItMjI2NmEzMDgtNzI4Yy00ZTQwLWIzZTYtNzE4ODE4YjBhZTU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTA5VDE0MDEwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZhMjdhZGU2YjZiOWJiYWMxY2M5MjhhMzJiNTg4M2YzNGM1N2M3MWU0M2RkZTcyZTBiNzI3YjNjZDUyY2VkYjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.qUp5kOxtReo-_vV380g5Z1ttfL-LinFANv0bR0twjrE) ![image](https://private-user-images.githubusercontent.com/67215274/401539243-fe4ea1bf-7520-456e-8be3-112b7dd5de65.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzY0MzE1NjYsIm5iZiI6MTczNjQzMTI2NiwicGF0aCI6Ii82NzIxNTI3NC80MDE1MzkyNDMtZmU0ZWExYmYtNzUyMC00NTZlLThiZTMtMTEyYjdkZDVkZTY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTA5VDE0MDEwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM0YzEyNjFkMDY0YTJhMTZlYjMwMTcyMzllYjgxOTYwYTM4OTE1ZWI5ZTRjMGQxMWVjOTliMmU3YWI4ZWMzOGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.W6drSkphlXV6qIwVBr-gZffPjSx89V2E2PXYLyODwlw)
> 
> If there is no `debug.log` in that directory, then ibus-typing-booster did never run on your system.

Do you know how can run it then?

**Comment by abirabedinkhan** [comment]
i upgraded to Bookworm but this device has some flaws with Bookworm. all ibus started working but still not working properly and I successfully added `ibus-typing-booster` to ibus.
```
  saplaos@BongoPC:~$ ibus list-engine | grep booster
  typing-booster - Typing Booster
```
also able to produce `debug.log`
```
saplaos@BongoPC:~$ tail -F ~/.local/share/ibus-typing-booster/debug.log

2025-01-10 00:02:09,912 itb_util.py line 3349 get_hunspell_dictionary_wordlist INFO: /usr/share/hunspell/en_US.dic file found.
2025-01-10 00:02:09,919 itb_util.py line 3373 get_hunspell_dictionary_wordlist INFO: dictionary encoding=UTF-8 found in /usr/share/hunspell/en_US.aff
2025-01-10 00:02:09,947 itb_util.py line 3415 get_hunspell_dictionary_wordlist INFO: Successfully loaded /usr/share/hunspell/en_US.dic using UTF-8 encoding.
2025-01-10 00:02:11,912 hunspell_table.py line 7049 on_gsettings_value_changed DEBUG: Settings changed: key=inputmethod value=NoIME

2025-01-10 00:02:11,945 hunspell_table.py line 778 __init__ INFO: *** ibus-typing-booster 2.22.0 initialized, ready for input: ***
2025-01-10 00:02:11,947 tabsqlitedb.py line 1292 cleanup_database INFO: Database cleanup starting ...
2025-01-10 00:02:11,995 itb_active_window.py line 317 get_active_window DEBUG: Got active window from xprop: ('xfdesktop', 'Desktop')
2025-01-10 00:02:12,037 itb_active_window.py line 317 get_active_window DEBUG: Got active window from xprop: ('xfdesktop', 'Desktop')
```

**Comment by abirabedinkhan** [comment]
well, m17n still not working with the update

**Comment by abirabedinkhan** [comment]
Hey, I downgraded to Debian Bullseye it has the same problem as Buster. I can't add "Typing Booster" to the Ibus engine.

**Comment by mike-fabian** [comment]
> i upgraded to Bookworm but this device has some flaws with Bookworm. all ibus started working but still not working properly and I successfully added `ibus-typing-booster` to ibus.
> 
> ```
>   saplaos@BongoPC:~$ ibus list-engine | grep booster
>   typing-booster - Typing Booster
> ```
> 
> also able to produce `debug.log`

That looks good!

**Comment by mike-fabian** [comment]
> well, m17n still not working with the update

Did you add bn-bijoyUnicode.mim in the typing booster setup tool?

**Comment by abirabedinkhan** [comment]
how can I add that?

**Comment by mike-fabian** [comment]
> how can I add that?

In the setup tool of ibus-typing-booster, in the “Dictionaries and input methods” tab add `bn-bijoyUnicode` and a dictionary if you like. Like this:

![Screenshot](https://github.com/user-attachments/assets/5e5acb5e-a708-4035-b8c5-e8fe4a53a2c5)
